### ISSUE TITLE
PSR-18 compatible clients

### ISSUE THREAD

**Issue by bonroyage** [MijnPartnerGroep-nl/sidn-suggestion-api-php#2]
In [PSR-18](https://www.php-fig.org/psr/psr-18/) wordt gesproken over een generieke ClientInterface, waarbij de gebruiker in staat zou zijn om elke (compliant) HTTP client, waaronder `guzzle`, `symfony/http-client`, te gebruiken om de requests uit te voeren. 

Ik ben ooit een library tegengekomen die dit netjes had opgelost (https://github.com/meilisearch/meilisearch-php, onderaan de readme). De gebruiker kan expliciet een HTTP client meegeven, of anders automatisch via discovery laat ophalen (zie Http/Client.php).

Hoe kijken jullie hier tegen aan?

**Comment by RobertVerboon** [comment]
@cswiers wat wil je met dit issue doen? Ik kreeg van SIDN de vraag hoe ver we zijn met de review, dus vandaar dat ik even wil checken in hoeverre we hier iets mee willen met z'n allen. Dank!

**Comment by cswiers** [comment]
Het implementeren van PSR-18 heeft wat ons betreft geen prioriteit. Wij hebben voor Guzzle gekozen omdat deze over het algemeen veel gebruikt wordt door libraries en applicaties.

**Comment by RobertVerboon** [comment]
Helemaal prima! Wat mij betreft kunnen we dit issue dan ook sluiten (tenzij jullie hem graag open laten staan voor een eventuele toekomstige aanpassing).

**Comment by cswiers** [comment]
Ik zal hem voor nu sluiten. Bedankt voor jullie input de afgelopen tijd!
