### ISSUE TITLE
API client: headers, equals, access token

### ISSUE THREAD

**Issue by bonroyage** [MijnPartnerGroep-nl/sidn-suggestion-api-php#4]
De `Accept` header in deze functie (regel 115) werkt niet, waarom zit de `$httpMethod` check daar?

De parameter `array $httpHeaders = null` zou je kun kunnen veranderen naar `array $httpHeaders = []`, zodat de if op regel 118 kan vervallen. Zonder eigen headers wordt er dan gewoon een lege array gemerged.

https://github.com/MijnPartnerGroep-nl/sidn-suggestion-api-php/blob/8fdaa528b3f8b7f705de90e3fb6f4e26d4bec060/src/SidnSuggestionApiClient.php#L108

https://github.com/MijnPartnerGroep-nl/sidn-suggestion-api-php/blob/8fdaa528b3f8b7f705de90e3fb6f4e26d4bec060/src/SidnSuggestionApiClient.php#L114-L123

---

Ook zou het netjes zijn om de strict operator (`===`/`!==`) te gebruiken ipv `==`/`!=`, zoals op regel 121, 137.

https://github.com/MijnPartnerGroep-nl/sidn-suggestion-api-php/blob/8fdaa528b3f8b7f705de90e3fb6f4e26d4bec060/src/SidnSuggestionApiClient.php#L121

https://github.com/MijnPartnerGroep-nl/sidn-suggestion-api-php/blob/8fdaa528b3f8b7f705de90e3fb6f4e26d4bec060/src/SidnSuggestionApiClient.php#L137

---

Is het nodig om de access token te trimmen? Zou dit niet eerder een verantwoordelijkheid zijn van de gebruiker om de juiste waarde mee te geven?

https://github.com/MijnPartnerGroep-nl/sidn-suggestion-api-php/blob/8fdaa528b3f8b7f705de90e3fb6f4e26d4bec060/src/SidnSuggestionApiClient.php#L168-L173

**Comment by cswiers** [comment]
De accesstoken ontvang je terug van de API, deze wordt niet door de gebruiker meegegeven. Andere punten zijn gewijzigd/toegepast.
