### ISSUE TITLE
Timestamps in API exception

### ISSUE THREAD

**Issue by bonroyage** [MijnPartnerGroep-nl/sidn-suggestion-api-php#5]
In de API exception wordt een timestamp toegevoegd aan de message. Waarom is hier voor gekozen? Elke logger zet de timestamp, samen met de error level, standaard voor de message neer. 

Aangezien je de timestamp ook uit de response kan krijgen, is het dan relevanter om de timestamp in een property te zetten zodat de developer hier zelf wat mee kan doen mocht hij dat willen?

https://github.com/MijnPartnerGroep-nl/sidn-suggestion-api-php/blob/8fdaa528b3f8b7f705de90e3fb6f4e26d4bec060/src/Exceptions/ApiException.php#L43-L53

**Comment by cswiers** [comment]
Misschien mooier nog om er een protected property van te maken met een public method? E.g. getTimestamp(), meer zoals de standaard exception methods.

**Comment by bonroyage** [comment]
> Misschien mooier nog om er een protected property van te maken met een public method? E.g. getTimestamp(), meer zoals de standaard exception methods.

Mee eens dat het mooier is als exceptions immutable zijn.
